/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ErrorCodes_CONSTANTS_H
#define ErrorCodes_CONSTANTS_H

#include "ErrorCodes_types.h"

namespace impala {

class ErrorCodesConstants {
 public:
  ErrorCodesConstants();

  std::vector<std::string>  TErrorMessage;
};

extern const ErrorCodesConstants g_ErrorCodes_constants;

} // namespace

#endif
