/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Metrics_TYPES_TCC
#define Metrics_TYPES_TCC

#include "Metrics_types.h"

namespace impala {

} // namespace

#endif
